overview:
	R -e "rmarkdown::render('overview.Rmd')"
	open overview.html

case_1:
	R -e "rmarkdown::render('caseStudyOne.Rmd')"
	open caseStudyOne.html



vigExtract:
	R -e "library(knitr); purl('overview.Rmd')"

